DROP INDEX IF EXISTS event_source_raw_hash_idx;
ALTER TABLE event_source DROP COLUMN IF EXISTS raw_hash;
ALTER TABLE source DROP COLUMN IF EXISTS last_ok_at, DROP COLUMN IF EXISTS fail_count;
ALTER TABLE venue DROP COLUMN IF EXISTS lat, DROP COLUMN IF EXISTS lng, DROP COLUMN IF EXISTS website;
